### PR TITLE
swap form link to new unified forms

### PR DESCRIPTION
**Pull request by woutervddn**
it's the same form as the other websites.

### CODE REVIEW

**Comment by lukin0110** [comment]
Someone in charge of merge the input of these forms?

**Comment by woutervddn** [comment]
I'm currently retesting the forms.
Next step is moving data from old forms to new forms as described here: https://github.com/MakeInBelgium/maskermatch/issues/17

**Comment by lukin0110** [comment]
Deze PR, mergen we die NU of na de migratie?

**Comment by woutervddn** [comment]
gemigreerd, merge maar :)

**Pull request merged**
